USE INNTEAL_ORGANIZER;

-- Añadir columna 'phone'
SELECT COUNT(*) INTO @exists FROM INFORMATION_SCHEMA.COLUMNS
 WHERE TABLE_SCHEMA='INNTEAL_ORGANIZER' AND TABLE_NAME='users' AND COLUMN_NAME='phone';
SET @sql = IF(@exists=0, 'ALTER TABLE users ADD COLUMN phone VARCHAR(30) DEFAULT NULL', 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- Añadir columna 'company'
SELECT COUNT(*) INTO @exists FROM INFORMATION_SCHEMA.COLUMNS
 WHERE TABLE_SCHEMA='INNTEAL_ORGANIZER' AND TABLE_NAME='users' AND COLUMN_NAME='company';
SET @sql = IF(@exists=0, 'ALTER TABLE users ADD COLUMN company VARCHAR(255) DEFAULT NULL', 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- Añadir columna 'role' (enum)
SELECT COUNT(*) INTO @exists FROM INFORMATION_SCHEMA.COLUMNS
 WHERE TABLE_SCHEMA='INNTEAL_ORGANIZER' AND TABLE_NAME='users' AND COLUMN_NAME='role';
SET @sql = IF(@exists=0, "ALTER TABLE users ADD COLUMN role ENUM('user','manager','admin') NOT NULL DEFAULT 'user'", 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- Añadir columna 'address'
SELECT COUNT(*) INTO @exists FROM INFORMATION_SCHEMA.COLUMNS
 WHERE TABLE_SCHEMA='INNTEAL_ORGANIZER' AND TABLE_NAME='users' AND COLUMN_NAME='address';
SET @sql = IF(@exists=0, 'ALTER TABLE users ADD COLUMN address TEXT DEFAULT NULL', 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- Añadir columna 'profile_url'
SELECT COUNT(*) INTO @exists FROM INFORMATION_SCHEMA.COLUMNS
 WHERE TABLE_SCHEMA='INNTEAL_ORGANIZER' AND TABLE_NAME='users' AND COLUMN_NAME='profile_url';
SET @sql = IF(@exists=0, 'ALTER TABLE users ADD COLUMN profile_url VARCHAR(255) DEFAULT NULL', 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- Añadir columna 'accept_terms'
SELECT COUNT(*) INTO @exists FROM INFORMATION_SCHEMA.COLUMNS
 WHERE TABLE_SCHEMA='INNTEAL_ORGANIZER' AND TABLE_NAME='users' AND COLUMN_NAME='accept_terms';
SET @sql = IF(@exists=0, 'ALTER TABLE users ADD COLUMN accept_terms TINYINT(1) NOT NULL DEFAULT 0', 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- Añadir columna 'last_login'
SELECT COUNT(*) INTO @exists FROM INFORMATION_SCHEMA.COLUMNS
 WHERE TABLE_SCHEMA='INNTEAL_ORGANIZER' AND TABLE_NAME='users' AND COLUMN_NAME='last_login';
SET @sql = IF(@exists=0, 'ALTER TABLE users ADD COLUMN last_login DATETIME DEFAULT NULL', 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- Añadir columna 'is_active'
SELECT COUNT(*) INTO @exists FROM INFORMATION_SCHEMA.COLUMNS
 WHERE TABLE_SCHEMA='INNTEAL_ORGANIZER' AND TABLE_NAME='users' AND COLUMN_NAME='is_active';
SET @sql = IF(@exists=0, 'ALTER TABLE users ADD COLUMN is_active TINYINT(1) NOT NULL DEFAULT 1', 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- Añadir columna 'updated_at'
SELECT COUNT(*) INTO @exists FROM INFORMATION_SCHEMA.COLUMNS
 WHERE TABLE_SCHEMA='INNTEAL_ORGANIZER' AND TABLE_NAME='users' AND COLUMN_NAME='updated_at';
SET @sql = IF(@exists=0, 'ALTER TABLE users ADD COLUMN updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP', 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
