USE INNTEAL_ORGANIZER;

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS phone VARCHAR(30) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS company VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS role ENUM('user','manager','admin') NOT NULL DEFAULT 'user',
  ADD COLUMN IF NOT EXISTS address TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS profile_url VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS accept_terms TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS last_login DATETIME DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS is_active TINYINT(1) NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP;
